language: python
python:
  - "2.7"

notifications:
  email: false
sudo: required
before_install:
 - sudo apt-get update
install: 
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install Gedi

