language: python
python:
  - "3.5"

notifications:
  email: false

sudo: required

before_install:
 - sudo apt-get update

install: 
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install emcee
  - pip install corner
  # and now the Gedi package
  - python setup.py install

script:
  - test.py
